const WorkData = [
  {
    id: "1",
    name: "BlackTech",
    JobTitle: "Independent Contractor",
    period: "01/06/2020 - 31/07/2020",
    position: "Junior",
    Role: "Flutter developer",
    RoleDiscription: "Flutter App Developer",
    CompanySite: "",
    DevTools: ["Flutter", "Gitlab"],
  },
  {
    id: "2",
    name: "Culture Systems",
    JobTitle: "Independent Contractor",
    period: "01/10/2019 - 29/02/2020",
    position: "Junior",
    Role: "Flutter developer",
    RoleDiscription: "Junior Flutter Developer",
    CompanySite: "",
    DevTools: ["Flutter", "BitBucket", "Jira"],
  },
  {
    id: "3",
    name: "Culture Systems",
    JobTitle: "Independent Contractor",
    period: "01/March/2019 - 30/June/2019",
    position: "Junior",
    RoleDiscription: "Front-end Developer",
    CompanySite: "",
    DevTools: [
      "HTML",
      "CSS",
      "JavaScript",
      "Bootstrap",
      "BitBucket",
      "Dust.js",
      "Jira",
      "Zeplin",
    ],
  },
  {
    id: "4",
    name: "NativeVML",
    JobTitle: "Intern",
    period: "01/February/2017 - 31/March/2018",
    position: "Intern",
    RoleDiscription: "Front-end Developer",
    CompanySite: "",
    DevTools: [
      "HTML",
      "CSS",
      "JavaScript",
      "Bootstrap",
      "BitBucket",
      "Dust.js",
      "Nunjunks.js",
      "Jira",
      "PhotoShop",
      "Illustrator",
    ],
  },
];

export default WorkData;
