const WorkData = [
  {
    id: "1",
    name: "NativeVML",
    JobTitle: "Intern",
    period: "",
    position: "Junior",
    RoleDiscription: "",
    CompanySite: "",
    DevTools: [
      "HTML",
      "CSS",
      "JavaScript",
      "Bootstrap",
      "BitBucket",
      "Dust.js",
      "Nunjunks.js",
      "Jira",
      "PhotoShop",
      "Illustrator",
    ],
  },
  {
    id: "2",
    name: "Culture Systems",
    JobTitle: "Independent Contractor",
    period: "",
    position: "Junior",
    RoleDiscription: "",
    CompanySite: "",
    DevTools: [
      "HTML",
      "CSS",
      "JavaScript",
      "Bootstrap",
      "BitBucket",
      "Dust.js",
      "Jira",
      "",
    ],
  },
  {
    id: "3",
    name: "Culture Systems",
    JobTitle: "Independent Contractor",
    period: "01/10/2019 - 29/02/2020",
    position: "Junior",
    Role: "Flutter developer",
    RoleDiscription: "",
    CompanySite: "",
    DevTools: ["Flutter", "BitBucket", "Jira"],
  },
  {
    id: "4",
    name: "BlackTech",
    JobTitle: "Independent Contractor",
    period: "01/06/2020 - 31/07/2020",
    position: "Junior",
    Role: "Flutter developer",
    RoleDiscription: "",
    CompanySite: "",
    DevTools: ["Flutter", "Gitlab"],
  },
];

export default WorkData;
